### PR TITLE
Add support for NaNs and custom min/mix values

### PR DESCRIPTION
**Pull request by pkazmier**
Data series may now contain NaNs. NaN values will print a space
character instead of a spark char to indicate missing data:

    $ python sparkline.py 1 2 Nan 4 5
    ▁▂ ▆█

Users can now specify the min and max values that data points will be
clamped to:

    $ python sparkline.py 1 2 Nan 4 5 --min 2 --max 4
    ▁▁ ██

Fix argparse use to allow users to specify command line flags either
before or after the data series:

    $ python sparkline.py 1 2 Nan 4 5 --min 2 --max 4
    $ python sparkline.py --min 2 --max 4 1 2 Nan 4 5

### CODE REVIEW

**Comment by pkazmier** [comment]
I added support for NaNs because I use sparkline with time series data that sometimes has missing data points. In addition, on a single page, I have many sparklines around vertically that all share the same time range, so it's important that values are plotted at the right location on the x-axis.

**Comment by RedKrieg** [comment]
Thanks for your commit.  I've decided to make this project Python3 only since Python2 is no longer supported.  Removed some utf handling code and updated the readme.

**Comment by pkazmier** [comment]
Great! I know that was preventing you from updating pypi.

**Comment by RedKrieg** [comment]
FYI - PyPI now has version 1.0 with Py3 support and your patches.

**Pull request merged**
